name: deploy operation-kino

on:
  workflow_dispatch:

env:
  APP: 'operation-kino'
  S3_BUCKET: 'allenmaygibson-artifacts'

permissions:
  id-token: write
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up py
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: package lambdas
        run: python package_lambda.py

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::025066267460:role/allenmaygibson-github-actions
          aws-region: ap-southeast-2

      - name: upload lambda packages to s3
        run: |
          aws s3 cp build/scrape_cinemas.zip s3://${{ env.S3_BUCKET }}/${{ env.APP }}/scrape_cinemas.zip
          aws s3 cp build/scrape_sessions.zip s3://${{ env.S3_BUCKET }}/${{ env.APP }}/scrape_sessions.zip
          aws s3 cp build/get_sessions.zip s3://${{ env.S3_BUCKET }}/${{ env.APP }}/get_sessions.zip
