name: deploy operation-kino

on:
  workflow_dispatch:

env:
  APP: 'operation-kino'
  AWS_REGION: 'ap-southeast-2'
  S3_BUCKET: 'allenmaygibson-artifacts'

permissions:
  id-token: write
  contents: read

jobs:
  package-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up py
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: package lambdas
        run: python package_lambda.py

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::025066267460:role/allenmaygibson-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: set up tf
        uses: hashicorp/setup-terraform@v3

      - name: tf init
        run: terraform init
        working-directory: infra

      - name: tf apply
        run: |
          terraform apply -auto-approve \
            -var="scrape_host_nz=${{ secrets.SCRAPE_HOST_NZ }}" \
            -var="scrape_host_au=${{ secrets.SCRAPE_HOST_AU }}"
        working-directory: infra   
