name: build and deploy operation-kino

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up py
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: package lambdas
        run: python package_lambda.py

      - name: show build content
        run: ls -R build/
        